#!/bin/bash
set -euo pipefail

# Build Release
# Build Release (project already generated by CI step)
xcodebuild -project XcodeProject/DNSChanger.xcodeproj -scheme DNSChanger -configuration Release -derivedDataPath DerivedData -destination "platform=macOS" build

APP_PATH="DerivedData/Build/Products/Release/DNSChanger.app"

mkdir -p Build
cp -R "$APP_PATH" Build/

# Codesign app with hardened runtime and timestamp
if [[ -z "${DEVELOPER_ID_APP:-}" ]]; then
  echo "DEVELOPER_ID_APP not set; skipping codesign."
  exit 0
fi

echo "Codesigning app at $APP_PATH with identity: $DEVELOPER_ID_APP"
/usr/bin/codesign --force --options runtime --timestamp --sign "$DEVELOPER_ID_APP" "$APP_PATH"

echo "Codesign verification:"
/usr/bin/codesign --verify --deep --strict --verbose=2 "$APP_PATH"
