name: DNSChanger
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  developmentLanguage: en

settings:
  base:
    PRODUCT_NAME: DNSChanger
    DEVELOPMENT_TEAM: TEAM_ID
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "Developer ID Application"
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    SWIFT_VERSION: 5.0
    ENABLE_HARDENED_RUNTIME: YES
    SUPPORTED_PLATFORMS: macosx
    SUPPORTED_ARCHS: "arm64 x86_64"
    ALWAYS_SEARCH_USER_PATHS: NO

packages: {}

configs:
  Debug: debug
  Release: release

targets:
  DNSChanger:
    type: application
    platform: macOS
    sources:
      - path: ../Sources/App
      - path: ../Sources/Shared
    resources:
      - path: ../Resources/config/default_profiles.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pacman.DNSChanger
        INFOPLIST_FILE: DNSChanger-Info.plist
        OTHER_CODE_SIGN_FLAGS: "--deep --timestamp"
      configs:
        Release:
          CODE_SIGN_IDENTITY: "$(DEVELOPER_ID_APP)"
    dependencies:
      - target: DNSChangerHelper
    preBuildScripts:
      - name: Inject Helper Code Requirement
        script: |
          set -euo pipefail
          HELPER_APP="${BUILT_PRODUCTS_DIR}/DNSChangerHelper"
          if [ -x "$HELPER_APP" ]; then
            REQ="$(/usr/bin/codesign -dr - "$HELPER_APP" 2>/dev/null | /usr/bin/sed 's/^designated => //' || true)"
            if [ -n "$REQ" ]; then
              /usr/libexec/PlistBuddy -c "Delete :SMPrivilegedExecutables:com.pacman.DNSChangerHelper" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" || true
              /usr/libexec/PlistBuddy -c "Add :SMPrivilegedExecutables:com.pacman.DNSChangerHelper string $REQ" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
            else
              echo "Helper not signed; skipping SMPrivilegedExecutables injection."
            fi
          fi
        basedOnDependencyAnalysis: false
    postBuildScripts:
      - name: Embed Helper into App Bundle
        script: |
          set -euo pipefail
          APP_CONTENTS="${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app/Contents"
          HELPER_SRC="${BUILT_PRODUCTS_DIR}/DNSChangerHelper"
          HELPER_DST="${APP_CONTENTS}/Library/LaunchServices/com.pacman.DNSChangerHelper"
          if [ -x "$HELPER_SRC" ]; then
            mkdir -p "$(dirname "$HELPER_DST")"
            /bin/cp -f "$HELPER_SRC" "$HELPER_DST"
            /bin/chmod 755 "$HELPER_DST"
          else
            echo "Helper executable not found at $HELPER_SRC; skipping embed."
          fi
        basedOnDependencyAnalysis: false

  DNSChangerHelper:
    type: tool
    platform: macOS
    sources:
      - path: ../Sources/Helper
      - path: ../Sources/Shared
    settings:
      base:
        PRODUCT_NAME: DNSChangerHelper
        PRODUCT_BUNDLE_IDENTIFIER: com.pacman.DNSChangerHelper
        MACH_O_TYPE: mh_execute
        INFOPLIST_FILE: ../Sources/Helper/Info.plist
        LAUNCHD_PLIST_OUTPUT_FORMAT: binary1
        CODE_SIGN_IDENTITY: "Developer ID Application"
        OTHER_CODE_SIGN_FLAGS: "--timestamp"
    postBuildScripts:
      - name: Create Launchd Plist
        script: |
          set -euo pipefail
          # Ensure helper is built as a launchd tool with Info.plist containing MachServices
          :
        basedOnDependencyAnalysis: false

schemes:
  DNSChanger:
    build:
      targets:
        DNSChanger: all
        DNSChangerHelper: all
    run:
      config: Release
    archive:
      config: Release
