##############################################
#        DNSChanger Proxy Configuration     #
##############################################

# Listen on localhost port 53535 (avoiding mDNS on 5353)
listen_addresses = ['127.0.0.1:53535']

# Maximum number of simultaneous client connections
max_clients = 250

# Use servers reachable over IPv4
ipv4_servers = true

# Use servers reachable over IPv6
ipv6_servers = true

# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = false

# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = true

# Use servers implementing the DNS-over-TLS protocol
dot_servers = true

# Require DNSSEC validation
require_dnssec = false

# Require servers to not log queries
require_nolog = false

# Require servers to not filter content
require_nofilter = false

# Server names to use (will be replaced dynamically)
# server_names = ['cloudflare', 'google']

# How long a DNS query will wait for a response, in milliseconds
timeout = 5000

# Keepalive for HTTP (HTTPS, HTTP/2, HTTP/3) queries, in seconds
keepalive = 30

# Load-balancing strategy: 'p2' (default), 'ph', 'first', or 'random'
lb_strategy = 'p2'

# Log level (0-6, 0 = no logs, 6 = very verbose)
log_level = 0

# Use the system logger (syslog on Unix, Event Log on Windows)
use_syslog = false

# Delay, in minutes, after which certificates are reloaded
cert_refresh_delay = 240

# DNSCrypt: Create a new, unique key for every single DNS query
# This may improve privacy but can also have a significant impact on CPU usage
# Only enable if you don't have a lot of network load
dnscrypt_ephemeral_keys = false

# TLS disable session tickets
tls_disable_session_tickets = false

# TLS 1.3 ciphersuites
tls_cipher_suite = [52392, 49195, 49199, 49196, 49200, 52393, 52394]

# Fallback resolvers (used for bootstrap)
# These are normal, non-encrypted DNS resolvers
fallback_resolvers = ['1.1.1.1:53', '8.8.8.8:53']

# Always use the fallback resolver before the system DNS
ignore_system_dns = true

# Maximum time (in seconds) to wait for network connectivity before initializing the proxy
netprobe_timeout = 60

# Address and port to try initializing a connection to, just to check if the network is up
netprobe_address = '1.1.1.1:53'

# Offline mode - Don't use any remote encrypted servers
offline_mode = false

# Automatic log files rotation
# log_files_max_size = 10
# log_files_max_age = 7
# log_files_max_backups = 1

# Bootstrap resolvers
bootstrap_resolvers = ['1.1.1.1:53', '8.8.8.8:53']

# Cache settings
cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

[query_log]
  # Log file for DNS queries
  # file = 'query.log'
  # format = 'tsv'

[nx_log]
  # Log file for NXDOMAIN responses
  # file = 'nx.log'
  # format = 'tsv'

[blocked_names]
  # Log file for blocked names
  # file = 'blocked-names.log'
  # format = 'tsv'

[blocked_ips]
  # Log file for blocked IPs
  # file = 'blocked-ips.log'
  # format = 'tsv'

[allowed_names]
  # Log file for allowed names
  # file = 'allowed-names.log'
  # format = 'tsv'

[allowed_ips]
  # Log file for allowed IPs
  # file = 'allowed-ips.log'
  # format = 'tsv'

# Static server definitions
# These will be dynamically generated by the app

[static.'cloudflare']
stamp = 'sdns://AgcAAAAAAAAABzEuMS4xLjEAEmRucy5jbG91ZGZsYXJlLmNvbQovZG5zLXF1ZXJ5'

[static.'cloudflare-security']
stamp = 'sdns://AgcAAAAAAAAADDEuMS4xLjIgMS4wLjAuMgASZG5zLmNsb3VkZmxhcmUuY29tCi9kbnMtcXVlcnk'

[static.'google']
stamp = 'sdns://AgUAAAAAAAAAACAe9iTP_15r07rd8_3b_epWVGfjdymdx-5mdRZvMAzBuQ5kbnMuZ29vZ2xlLmNvbQ0vZXhwZXJpbWVudGFs'

[static.'quad9']
stamp = 'sdns://AgEAAAAAAAAAACA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OBBkbnM5LnF1YWQ5Lm5ldDo0NDMKL2Rucy1xdWVyeQ'

[static.'adguard']
stamp = 'sdns://AgcAAAAAAAAADzk0LjE0MC4xNC4xNDo0NDMAD2Rucy5hZGd1YXJkLmNvbQovZG5zLXF1ZXJ5'

[static.'nextdns']
stamp = 'sdns://AgcAAAAAAAAAAAAPZG5zLm5leHRkbnMuaW8KL2Rucy1xdWVyeQ'
