#!/bin/bash
set -euo pipefail

# Build Release
# Build Release (project already generated by CI step)
xcodebuild -project XcodeProject/DNSChanger.xcodeproj -scheme DNSChanger -configuration Release -derivedDataPath DerivedData -destination "platform=macOS" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO build

APP_PATH="DerivedData/Build/Products/Release/DNSChanger.app"
BUILD_DIR="Build"
BUILD_APP_PATH="${BUILD_DIR}/DNSChanger.app"

mkdir -p "$BUILD_DIR"
rm -rf "$BUILD_APP_PATH"
cp -R "$APP_PATH" "$BUILD_APP_PATH"

# Codesign app with hardened runtime and timestamp
if [[ -z "${DEVELOPER_ID_APP:-}" ]]; then
  echo "DEVELOPER_ID_APP not set; skipping codesign."
  exit 0
fi

if ! /usr/bin/security find-identity -p codesigning -v | /usr/bin/grep -q "${DEVELOPER_ID_APP}"; then
  echo "Signing identity '${DEVELOPER_ID_APP}' not found in keychain; skipping codesign."
  exit 0
fi

echo "Codesigning app at $BUILD_APP_PATH with identity: $DEVELOPER_ID_APP"
/usr/bin/codesign --force --options runtime --timestamp --sign "$DEVELOPER_ID_APP" "$BUILD_APP_PATH"

echo "Codesign verification:"
/usr/bin/codesign --verify --deep --strict --verbose=2 "$BUILD_APP_PATH"
